[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/app/auth/:splat"
  status = 200

[[redirects]]
  from = "/cases/*"
  to = "/.netlify/functions/app/cases/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
